FROM rayproject/ray-ml
RUN sudo apt-get -y -q update
RUN sudo apt-get -y -q install vim-tiny # for looking at files

COPY ./entry_point_head.sh /entry_point_head.sh
RUN sudo chmod 755 /entry_point_head.sh

VOLUME /host
WORKDIR /host

ENTRYPOINT ["/bin/bash", "/entry_point_head.sh"]
