FROM rayproject/ray:nightly
RUN apt-get -y -q update
RUN apt-get -y -q install vim-tiny # for looking at files
# install the packages we will need for our demos
RUN conda install scikit-learn jupyter ipython

COPY ./entry_point_worker.sh /entry_point_worker.sh
RUN chmod 755 /entry_point_worker.sh

VOLUME /host
WORKDIR /host

ENTRYPOINT ["/bin/bash", "/entry_point_worker.sh"]
